services:
  postgres:
    image: postgres:15
    container_name: graphQL-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project3
    ports:
      - "5433:5432"
    volumes:
      - pgdata_project3:/var/lib/postgresql/data

volumes:
  pgdata_project3:
